[package]
name = "minipre"
version = "0.2.0"
authors = ["Diggory Blake <diggsey@googlemail.com>"]
description = "Minimal C-preprocessor in Rust"
repository = "https://github.com/Diggsey/minipre"
license = "MIT OR Apache-2.0"
edition = "2015"

[dependencies]
regex = "1.3.1"
